imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    
doctrine:
    dbal:
        connections:
            default:
                driver:   %test_database_driver%
                host:     %test_database_host%
                port:     %test_database_port%
                dbname:   %test_database_name%
                user:     %test_database_user%
                password: %test_database_password%
                

#
# MinkBundle configuration
#
mink:
    base_url: http://www.sfynx.local/
    selenium2: ~
    browser_name: firefox 
    
#
# SfynxBehatBundle configuration
#
sfynx_behat:
    servers: [local, dev]
    locales: [en, fr, ar]
    options:
        server: local
        locale: en 
