parameters:
    oradmin.admin.handler.login.dispatcher.changeredirection.class: OrApp\OrCmfBundle\EventListener\DispatcherLoginRedirection
    oradmin.admin.handler.login.dispatcher.changeresponse.class: OrApp\OrCmfBundle\EventListener\DispatcherLoginResponse
    oradmin.admin.handler.logout.dispatcher.changeresponse.class: OrApp\OrCmfBundle\EventListener\DispatcherLogoutResponse
    
    oradmin.admin.handler.login.class: OrApp\OrCmfBundle\EventListener\HandlerLogin

services:
    #
    # configuration of the pi event classes
    #             
    or_admin.dispatcher.login_handler.change_redirection:
        class: %oradmin.admin.handler.login.dispatcher.changeredirection.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: pi.handler.login.changeredirection, method: onPiLoginChangeRedirection, priority: 1 }  
            
    or_admin.dispatcher.login_handler.change_response:
        class: %oradmin.admin.handler.login.dispatcher.changeresponse.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: pi.handler.login.changeresponse, method: onPiLoginChangeResponse, priority: 1 }
            
    or_admin.dispatcher.logout_handler.change_response:
        class: %oradmin.admin.handler.logout.dispatcher.changeresponse.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: pi.handler.logout.changeresponse, method: onPiLogoutChangeResponse, priority: 1 }            
            
    #
    # configuration of the listener classes
    #        
    or_admin.login_handler:
        class: %oradmin.admin.handler.login.class%
        arguments: ["@logger", @security.context, @event_dispatcher, @doctrine, @service_container]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: monolog.logger , channel: user } 
            