security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern:      .*
            form_login:
                provider:       fos_userbundle
                login_path:     /myapp/login
                use_forward:    false
                check_path:     /myapp/login_check
                failure_path:   null
                default_target_path: /myapp
            logout:
                path:   /myapp/logout
                target: /myapp
            anonymous:    true
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPERADMIN: ROLE_ADMIN

    access_control:
        # Liste des pages accessibles Ã  tous les utilisateurs (ne pas toucher)
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resseting$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # PAGES ACCESSIBLES AUX ADMINISTRATEURS
        - { path: ^/myapp/admin/, role: ROLE_ADMIN }
        
        # PAGES ACCESSIBLES AUX UTILISATEURS CONNECTES
        - { path: ^/myapp/change-password, role: ROLE_USER }

        # PAGES ACCESSIBLES A TOUS
        - { path: ^/myapp.*, role: IS_AUTHENTICATED_ANONYMOUSLY }